version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-book-converter
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    # Если нужны webhooks, раскомментируйте:
    # ports:
    #   - "8000:8000"
    
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

# Если нужен Redis для кеширования (опционально)
  # redis:
  #   image: redis:7-alpine
  #   container_name: telegram-bot-redis
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/data

# volumes:
#   redis_data:
